In [2]:
import numpy as np

In [6]:
# Sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def gradient_descent(X, y, theta, learning_rate, iterations):
    # Make a copy of the original theta values
    theta_copy = theta.copy()

    for i in range(iterations):
        p = sigmoid(np.dot(X, theta_copy))
        gradient = np.dot(X.T, (p - y))
        # Update the copy of theta
        theta_copy -= learning_rate * gradient

    return theta_copy

In [7]:
# Example usage:
X = np.array([[4, 4,1],[6,4,1] ,[6,5,1], [6,8,1], [6,10,1], [8, 8,1], [8, 10,1]])  # feature matrix
y = np.array([1,1,1,0,0,1,0])  # labels
theta_0 = np.array([0.3, -0.2, 0.7])  # initial parameters
learning_rate = 0.01

In [8]:
#first iteration
print(theta_0)
theta = gradient_descent(X, y, theta_0, learning_rate, 1)
print(theta)
y_pred = np.round(sigmoid(np.dot(X, theta)))
correct_predictions = np.sum(y_pred == y)
print(correct_predictions)

[ 0.3 -0.2  0.7]
[ 0.20477175 -0.35426438  0.68685387]
6


In [9]:
#second iteration
print(theta_0)
theta = gradient_descent(X, y, theta_0, learning_rate, 2)
print(theta)
y_pred = np.round(sigmoid(np.dot(X, theta)))
correct_predictions = np.sum(y_pred == y)
print(correct_predictions)

[ 0.3 -0.2  0.7]
[ 0.10954349 -0.50852876  0.67370775]
3


In [10]:
#third iteration
theta = gradient_descent(X, y, theta_0, learning_rate, 3)
print(theta)
y_pred = np.round(sigmoid(np.dot(X, theta)))
correct_predictions = np.sum(y_pred == y)
print(correct_predictions)

[ 0.01431524 -0.66279314  0.66056162]
3


In [ ]:
P = np.array([[3,3,1],[4,10,1],[9,8,1],[9,10,1]])
y_pred = np.round(sigmoid(np.dot(P, theta)))
print(y_pred)